// Code generated by MockGen. DO NOT EDIT.
// Source: shipping/routing/routing.go

// Package mock_routing is a generated GoMock package.
package mock_routing

import (
	reflect "reflect"

	cargo "github.com/go-kit/examples/shipping/cargo"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// FetchRoutesForSpecification mocks base method.
func (m *MockService) FetchRoutesForSpecification(rs cargo.RouteSpecification) []cargo.Itinerary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRoutesForSpecification", rs)
	ret0, _ := ret[0].([]cargo.Itinerary)
	return ret0
}

// FetchRoutesForSpecification indicates an expected call of FetchRoutesForSpecification.
func (mr *MockServiceMockRecorder) FetchRoutesForSpecification(rs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRoutesForSpecification", reflect.TypeOf((*MockService)(nil).FetchRoutesForSpecification), rs)
}
